const path = require('path')

module.exports = {
    outputDir: path.resolve(__dirname, '../server/public'),
    devServer:{
        proxy:{
            '':{
                target:'http://localhost:3000/',
            },
            '/year':{
                target:'http://localhost:3000/year',
            } , 
            '/four':{
                target:'http://localhost:3000/four',
            }, 
            '/four/year':{
                target:'http://localhost:3000/four/year',
            },
            '/six':{
                target:'http://localhost:3000/six',
            }, 
            '/six/year':{
                target:'http://localhost:3000/six/year',
            },
            '/man-of-the-match':{
                target:'http://localhost:3000/man-of-the-match',
            }, 
            '/man-of-the-match/year':{
                target:'http://localhost:3000/man-of-the-match/year',
            },   
            '/successful-teams':{
                target:'http://localhost:3000/successful-teams',
            }, 
            '/successful-teams/year':{
                target:'http://localhost:3000/successful-teams/year',
            },
            '/toss':{
                target:'http://localhost:3000/toss',
            }, 
            '/toss/year':{
                target:'http://localhost:3000/toss/year',
            },
            '/decision':{
                target:'http://localhost:3000/decision',
            }, 
            '/decision/year':{
                target:'http://localhost:3000/decision/year',
            }, 
            '/dots':{
                target:'http://localhost:3000/dots',
            }, 
            '/dots/year':{
                target:'http://localhost:3000/dots/year',
            }, 
            '/extras':{
                target:'http://localhost:3000/extras',
            }, 
            '/extras/year':{
                target:'http://localhost:3000/extras/year',
            },   
        }
    }
};